version: '3.8'
services:
  cache:
    image: redis:6.2.5-alpine
    restart: always
    command: redis-server --requirepass xxx_redis_password
    ports:
     - '6380:6379'
    environment:
     - REDIS_REPLICATION_MODE=master
    volumes:
     - aib-redis:/var/lib/redis
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: 'aib'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'xxx_user_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'xxx_root_password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    # Where our data will be persisted
    volumes:
      - aib-mysql:/var/lib/mysql
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - aib-dynamo:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '3500:3500'
    volumes:
      # enables hot reloading
      - ./src:/var/www/aib/src
      # sync local fs to container
      - ./public:/var/www/aib/public
      # sync views
      - ./views:/var/www/aib/views

volumes:
  aib-redis:
  aib-mysql:
  aib-dynamo: {}
